const Permissions = {
  USERS_VIEW: 'USERS_VIEW',
  USERS_ADD: 'USERS_ADD',
  ANNOUNCEMENT_VIEW: 'ANNOUNCEMENT_VIEW',
  ANNOUNCEMENT_ADD: 'ANNOUNCEMENT_ADD',
  PROCESS_DOCUMENT_REQUESTS: 'PROCESS_DOCUMENT_REQUESTS',
  VIEW_DOCUMENT_REQUESTS: 'VIEW_DOCUMENT_REQUESTS',
  VIEW_NOTIFICATION_LOGS: 'VIEW_NOTIFICATION_LOGS',
  MY_PROFILE: 'MY_PROFILE',
  DASHBOARD: 'DASHBOARD',

  
  REQUEST_DOCUMENT: 'REQUEST_DOCUMENT',
  REQUEST_DOCUMENT_HISTORY: 'REQUEST_DOCUMENT_HISTORY',
  ANNOUNCEMENT_HISTORY: 'ANNOUNCEMENT_HISTORY',
};

export default Permissions;